# Ultralytics YOLO 🚀, AGPL-3.0 license
# CattleEyeView dataset (https://github.com/AnimalEyeQ/CattleEyeView)

# Task
task: multitask

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
## Change path to your images and annotations root folder
path: C:/Users/nikhi/Desktop/CattleData  # dataset root dir
train: ./images/train # train images (relative to 'path') 118287 images
val: ./images/val # val images (relative to 'path') 5000 images

# Image size
imgsz: [1920, 1080]

# Keypoints
kpt_shape: [24, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)

list_keypoints: &id001 [head, nose, eyeL, eyeR, earbaseL, eartipL, earbaseR, eartipR, neck, withers, elbowFL, kneeFL, pawFL, elbowFR, kneeFR, pawFR, elbowBL, kneeBL, pawBL, elbowBR, kneeBR, pawBR, tailbase, tailend]

flip_idx: [0, 1, 3, 2, 6, 7, 4, 5, 8, 9, 13, 14, 15, 10, 11, 12, 19, 20, 21, 16, 17, 18, 22, 23]

# Classes
names:
  0: cow


